version: '3.8' 
 
services: 
  licensing: 
    image: mcr.microsoft.com/dotnet/samples:aspnetapp 
    ports: 
      - "5001:80" 
 
  appointment: 
    image: mcr.microsoft.com/dotnet/samples:aspnetapp 
    ports: 
      - "5002:80" 
 
  billing: 
    image: mcr.microsoft.com/dotnet/samples:aspnetapp 
    ports: 
      - "5003:80" 
